# Generated by Django 4.2.3 on 2023-07-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('confirm_password', models.CharField(max_length=100)),
                ('phone_number', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('sectors', models.TextField()),
                ('resume', models.FileField(blank=True, upload_to='')),
                ('terms_condition', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': '1. Candidates',
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('confirm_password', models.CharField(max_length=100)),
                ('phone_number', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('organization_name', models.CharField(max_length=250)),
                ('terms_condition', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': '2. Employers',
            },
        ),
    ]
