# Generated by Django 4.2.3 on 2023-08-11 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('confirm_password', models.CharField(max_length=100)),
                ('phone_number', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('sectors', models.TextField()),
                ('resume', models.FileField(blank=True, upload_to='')),
                ('terms_condition', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': '1. Candidates',
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(max_length=300, unique=True)),
                ('sector', models.TextField()),
                ('established_date', models.DateField()),
                ('contact_number', models.PositiveBigIntegerField()),
                ('company_profile_img', models.ImageField(upload_to='images/company_profile/')),
                ('facebook_link', models.URLField(blank=True, null=True, unique=True)),
                ('twitter_link', models.URLField(blank=True, null=True, unique=True)),
                ('linkedin_link', models.URLField(blank=True, null=True, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=150)),
                ('postal_code', models.CharField(max_length=100)),
                ('exact_location', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': '7. CompanyProfiles',
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('confirm_password', models.CharField(max_length=100)),
                ('phone_number', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('organization_name', models.CharField(max_length=250)),
                ('terms_condition', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': '2. Employers',
            },
        ),
        migrations.CreateModel(
            name='JobSector',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': '3. JobSectors',
            },
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': '4. JobTypes',
            },
        ),
        migrations.CreateModel(
            name='SalaryType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': '5. SalaryTypes',
            },
        ),
        migrations.CreateModel(
            name='PostJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('application_deadline', models.DateTimeField()),
                ('required_skills', models.TextField()),
                ('salary_minimum', models.PositiveIntegerField()),
                ('salary_maximum', models.PositiveIntegerField()),
                ('job_image', models.ImageField(null=True, upload_to='images/jobs/')),
                ('experience', models.CharField(default='', max_length=255)),
                ('Qualification', models.CharField(default='', max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=150)),
                ('postal_code', models.CharField(max_length=100)),
                ('exact_location', models.CharField(max_length=250)),
                ('terms_conditions', models.BooleanField(default=False)),
                ('Industry', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.jobsector')),
                ('employer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.employer')),
                ('job_sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_sector', to='main.jobsector')),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.jobtype')),
                ('salary_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.salarytype')),
            ],
            options={
                'verbose_name_plural': '6. PostJobs',
            },
        ),
    ]
