# Generated by Django 4.2.3 on 2023-08-11 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postjob',
            name='Industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.jobsector'),
        ),
    ]
