# Generated by Django 4.2.3 on 2023-08-10 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_jobsector_jobtype_salarytype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobsector',
            options={'verbose_name_plural': '3. JobSectors'},
        ),
        migrations.AlterModelOptions(
            name='jobtype',
            options={'verbose_name_plural': '4. JobTypes'},
        ),
        migrations.AlterModelOptions(
            name='salarytype',
            options={'verbose_name_plural': '5. SalaryTypes'},
        ),
        migrations.CreateModel(
            name='PostJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('application_deadline', models.DateTimeField()),
                ('required_skills', models.TextField()),
                ('salary_minimun', models.IntegerField()),
                ('salary_maximun', models.IntegerField()),
                ('job_image', models.ImageField(upload_to='images/jobs/')),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=150)),
                ('postal_code', models.CharField(max_length=100)),
                ('exact_location', models.CharField(max_length=250)),
                ('terms_conditions', models.BooleanField(default=False)),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.jobtype')),
                ('salary_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.salarytype')),
            ],
        ),
    ]
