# Generated by Django 4.2.3 on 2023-08-11 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_industry_alter_postjob_industry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'verbose_name_plural': '8. CompanyProfiles'},
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'verbose_name_plural': '6. Industries'},
        ),
        migrations.AlterModelOptions(
            name='postjob',
            options={'verbose_name_plural': '7. PostJobs'},
        ),
    ]
