# Generated by Django 4.2.3 on 2023-08-10 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_jobsector_options_alter_jobtype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postjob',
            options={'verbose_name_plural': '5. PostJobs'},
        ),
    ]
