# Generated by Django 4.2.3 on 2023-08-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_postjob_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(max_length=300, unique=True)),
                ('sector', models.TextField()),
                ('established_date', models.DateField()),
                ('contact_number', models.PositiveBigIntegerField()),
                ('company_profile_img', models.ImageField(upload_to='images/company_profile/')),
                ('facebook_link', models.URLField(blank=True, null=True, unique=True)),
                ('Twitter_link', models.URLField(blank=True, null=True, unique=True)),
                ('Linkedin_link', models.URLField(blank=True, null=True, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=150)),
                ('postal_code', models.CharField(max_length=100)),
                ('exact_location', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': '7. CompanyProfiles',
            },
        ),
        migrations.AlterModelOptions(
            name='postjob',
            options={'verbose_name_plural': '6. PostJobs'},
        ),
        migrations.AlterField(
            model_name='postjob',
            name='salary_maximun',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='postjob',
            name='salary_minimun',
            field=models.PositiveIntegerField(),
        ),
    ]
