# Generated by Django 4.2.3 on 2023-08-11 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_companyprofile_options_alter_industry_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postjob',
            old_name='Industry',
            new_name='industry',
        ),
    ]
