# Generated by Django 4.2.3 on 2023-08-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_industry_postjob_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='company_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
