# Generated by Django 4.2.3 on 2023-08-10 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_companyprofile_alter_postjob_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='employer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.employer'),
        ),
    ]
