# Generated by Django 4.2.3 on 2023-08-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_companyprofile_company_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_profile_img',
            field=models.ImageField(blank=True, upload_to='images/company_profile/'),
        ),
    ]
