# Generated by Django 4.2.3 on 2023-08-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_companyprofile_company_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
