# Generated by Django 4.2.3 on 2023-08-14 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_postjob_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.companyprofile'),
        ),
    ]
