# Generated by Django 4.2.3 on 2023-08-15 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_postjob_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateJobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_time', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_candidates', to='main.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appied_jobs', to='main.postjob')),
            ],
            options={
                'verbose_name_plural': '8. CandidateJobApplications',
            },
        ),
    ]
