# Generated by Django 4.2.3 on 2023-08-15 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_candidate_id_alter_candidatejobapplication_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatejobapplication',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applied_candidates', to='main.candidate'),
        ),
    ]
