# Generated by Django 4.2.3 on 2023-08-15 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_candidatejobapplication_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatejobapplication',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appied_jobs', to='main.postjob'),
        ),
    ]
