# Generated by Django 4.2.3 on 2023-08-15 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_candidatejobapplication_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatejobapplication',
            name='candidate',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='applied_candidates', to='main.candidate'),
        ),
        migrations.AlterField(
            model_name='candidatejobapplication',
            name='job',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='appied_jobs', to='main.postjob'),
        ),
    ]
