# Generated by Django 4.2.3 on 2023-08-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_candidatejobapplication_candidate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='confirm_password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
