# Generated by Django 4.2.3 on 2023-08-19 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_candidate_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostInternship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('application_deadline', models.DateTimeField()),
                ('required_skills', models.TextField()),
                ('salary_minimum', models.PositiveIntegerField()),
                ('salary_maximum', models.PositiveIntegerField()),
                ('internship_image', models.ImageField(null=True, upload_to='images/internships/')),
                ('experience', models.CharField(max_length=255)),
                ('Qualification', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=150)),
                ('postal_code', models.CharField(max_length=100)),
                ('exact_location', models.CharField(max_length=250)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('terms_conditions', models.BooleanField(default=False)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.companyprofile')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employer')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.industry')),
                ('internship_sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_sector', to='main.jobsector')),
                ('internship_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.jobtype')),
                ('salary_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.salarytype')),
            ],
            options={
                'verbose_name_plural': '9. PostInternship',
            },
        ),
    ]
