# Generated by Django 4.2.3 on 2023-08-19 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_postinternship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidatejobapplication',
            options={'verbose_name_plural': '9. CandidateJobApplications'},
        ),
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'verbose_name_plural': '7. CompanyProfiles'},
        ),
        migrations.AlterModelOptions(
            name='postinternship',
            options={'verbose_name_plural': '10. PostInternship'},
        ),
        migrations.AlterModelOptions(
            name='postjob',
            options={'verbose_name_plural': '8. PostJobs'},
        ),
        migrations.RenameField(
            model_name='postinternship',
            old_name='Qualification',
            new_name='qualification',
        ),
        migrations.RenameField(
            model_name='postjob',
            old_name='Qualification',
            new_name='qualification',
        ),
    ]
