# Generated by Django 4.2.3 on 2023-08-19 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_candidatejobapplication_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'verbose_name_plural': '2. CompanyProfiles'},
        ),
        migrations.AlterModelOptions(
            name='employer',
            options={'verbose_name_plural': '3. Employers'},
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'verbose_name_plural': '7. Industries'},
        ),
        migrations.AlterModelOptions(
            name='jobsector',
            options={'verbose_name_plural': '4. JobSectors'},
        ),
        migrations.AlterModelOptions(
            name='jobtype',
            options={'verbose_name_plural': '5. JobTypes'},
        ),
        migrations.AlterModelOptions(
            name='salarytype',
            options={'verbose_name_plural': '6. SalaryTypes'},
        ),
        migrations.AddField(
            model_name='employer',
            name='companyProfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to='main.companyprofile'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='organization_name',
            field=models.CharField(max_length=200),
        ),
    ]
