# Generated by Django 4.2.3 on 2023-08-19 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_companyprofile_options_alter_employer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postinternship',
            name='company_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.companyprofile'),
        ),
    ]
