# Generated by Django 4.2.3 on 2023-08-19 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_postinternship_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postinternship',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.industry'),
        ),
    ]
