# Generated by Django 4.2.3 on 2023-08-19 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_postinternship_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postinternship',
            name='internship_sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internship_sector', to='main.jobsector'),
        ),
    ]
