# Generated by Django 4.2.3 on 2023-08-19 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_postinternship_internship_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postinternship',
            name='internship_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.jobtype'),
        ),
        migrations.AlterField(
            model_name='postinternship',
            name='salary_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.salarytype'),
        ),
    ]
