# Generated by Django 4.2.3 on 2023-08-25 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_postinternship_internship_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=400)),
                ('mail', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '12. Contacts',
            },
        ),
        migrations.CreateModel(
            name='CandidateInternshipApplication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('applied_time', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.candidate')),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appied_internship', to='main.postinternship')),
            ],
            options={
                'verbose_name_plural': '11. CandidateInternshipApplications',
            },
        ),
    ]
